name: ESP Heartbeat Monitor

on:
  schedule:
    # Запуск каждые 2 минуты
    - cron: "*/5 * * * *"
  workflow_dispatch:   # Ручной запуск по кнопке

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      # 4️⃣ Запускаем мониторинг
      - name: Run monitor
        run: |
          python monitor.py
