name: ESP Heartbeat Monitor

on:
  schedule:
    # запуск каждые 5 минут (максимально быстро для GitHub Actions)
    - cron: "*/5 * * * *"
  workflow_dispatch:   # кнопка для ручного запуска

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ Запускаем monitor.py с передачей секретов и Firebase URL
      - name: Run monitor.py
        run: python monitor.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FIREBASE_URL: https://heartbeat-kamaleeva-default-rtdb.firebaseio.com/heartbeat.json
